name: Build


on:
  push:
    paths:
      - '**.py'
      - '**.yml'
  
  pull_request:
    paths:
      - '**.py'
      - '**.yml'

  workflow_dispatch:


jobs:
  build:
    runs-on: windows-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python 3.9
      uses: actions/setup-python@v4.7.1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Build
      run: flet pack main.py --name "amazing_optimizer" --distpath . --icon assets\logo.png

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: windows-build
        path: amazing_optimizer.exe
        retention-days: 2
